// Doom Perf: anti-aliased menu text for the 640x400 and 960x600 engines.
//
// The glyphs (wasm/menu_font_data.h, generated by scripts/gen-menu-font.py) are
// Chakra Petch on a coarse pixel grid with the HUD font's treatment: each glyph
// pixel is a DP_MF_*_PIX square block, ink is shaded top-to-bottom, and a dark
// one-pixel outline (darkened through COLORMAP) keeps the text readable over
// the flame-graph title and the game view alike. Outlines for a whole line go
// down before any ink so a tight neighbour's outline never bites a letter.
//
// Positions are in Doom's 320x200 UI units, like the rest of the menu. `y` is the
// top of the capitals, which is where M_WriteText's 7-unit capitals start too, so
// layouts line up whichever font is in use. The 320x200 engine has no data here
// (DoomPerf_MenuFontAvailable() == 0) and m_menu.c falls back to the HUD font.

#include "doomdef.h"
#include "doomtype.h"
#include "r_local.h"
#include "v_video.h"
#include "w_wad.h"
#include "z_zone.h"

#include "menu_font_data.h"

#if DP_MF_AVAILABLE

#define DP_MF_SCALE    (SCREENWIDTH / 320)
#define DP_MF_TONES    2
#define DP_MF_OUTLINE  28       // COLORMAP level for outline pixels (31 = black)

// Palette entry per tone and ink brightness level (2..15).
static unsigned char dp_mf_ink[DP_MF_TONES][16];
static int dp_mf_built = 0;

// Tone targets: 0 = bright cool white (items, current screen), 1 = slate (meta).
static const int dp_mf_tone_rgb[DP_MF_TONES][3] =
{
    {236, 240, 248},
    {150, 160, 178}
};

static void DP_MF_Build(void)
{
    const byte* pal = (const byte*)W_CacheLumpName("PLAYPAL", PU_CACHE);
    int tone, level, j;

    for (tone = 0; tone < DP_MF_TONES; tone++)
	for (level = 0; level < 16; level++)
	{
	    int tr = dp_mf_tone_rgb[tone][0] * level / 15;
	    int tg = dp_mf_tone_rgb[tone][1] * level / 15;
	    int tb = dp_mf_tone_rgb[tone][2] * level / 15;
	    int best = 0;
	    long bd = 0x7fffffffL;
	    for (j = 0; j < 256; j++)
	    {
		int dr = pal[j * 3] - tr;
		int dg = pal[j * 3 + 1] - tg;
		int db = pal[j * 3 + 2] - tb;
		long d = (long)dr * dr + (long)dg * dg + (long)db * db;
		if (d < bd) { bd = d; best = j; }
	    }
	    dp_mf_ink[tone][level] = (unsigned char)best;
	}
    dp_mf_built = 1;
}

static const dp_mf_glyph_t* DP_MF_Glyphs(int style)
{
    return style ? dp_mf_small_glyphs : dp_mf_item_glyphs;
}

static const unsigned char* DP_MF_Data(int style)
{
    return style ? dp_mf_small_data : dp_mf_item_data;
}

static int DP_MF_Cap(int style)
{
    return style ? DP_MF_SMALL_CAP : DP_MF_ITEM_CAP;
}

static int DP_MF_Pix(int style)
{
    return style ? DP_MF_SMALL_PIX : DP_MF_ITEM_PIX;
}

static int DP_MF_Level(const unsigned char* data, const dp_mf_glyph_t* g, int gx, int gy)
{
    int i = gy * g->w + gx;
    unsigned char b = data[g->ofs + (i >> 1)];
    return (i & 1) ? (b >> 4) : (b & 15);
}

// One pass over a line of text, in framebuffer pixels: outline != 0 draws only
// the outline pixels, otherwise only the ink.
static void DP_MF_Pass(int px, int baseline, int style, int tone, const char* s, int outline)
{
    const dp_mf_glyph_t* glyphs = DP_MF_Glyphs(style);
    const unsigned char* data = DP_MF_Data(style);
    const dp_mf_glyph_t* g;
    int pix = DP_MF_Pix(style);
    int c, gx, gy, bx, by, x, y, level;
    byte* dest;

    for (; (c = (unsigned char)*s); s++)
    {
	if (c < DP_MF_FIRST || c > DP_MF_LAST)
	    c = '?';
	g = &glyphs[c - DP_MF_FIRST];
	for (gy = 0; gy < g->h; gy++)
	    for (gx = 0; gx < g->w; gx++)
	    {
		level = DP_MF_Level(data, g, gx, gy);
		if (!level || (level == 1) != !!outline)
		    continue;
		for (by = 0; by < pix; by++)
		{
		    y = baseline + (g->yoff + gy) * pix + by;
		    if ((unsigned)y >= SCREENHEIGHT)
			continue;
		    for (bx = 0; bx < pix; bx++)
		    {
			x = px + (g->xoff + gx) * pix + bx;
			if ((unsigned)x >= SCREENWIDTH)
			    continue;
			dest = &screens[0][y * SCREENWIDTH + x];
			*dest = outline ? colormaps[DP_MF_OUTLINE * 256 + *dest]
					: dp_mf_ink[tone][level];
		    }
		}
	    }
	px += g->adv * pix;
    }
}

int DoomPerf_MenuFontAvailable(void)
{
    return 1;
}

int DoomPerf_MenuTextWidth(int style, const char* s)
{
    const dp_mf_glyph_t* glyphs = DP_MF_Glyphs(style);
    int c, w = 0;

    for (; (c = (unsigned char)*s); s++)
    {
	if (c < DP_MF_FIRST || c > DP_MF_LAST)
	    c = '?';
	w += glyphs[c - DP_MF_FIRST].adv;
    }
    w *= DP_MF_Pix(style);
    return (w + DP_MF_SCALE - 1) / DP_MF_SCALE;
}

// Draws `s` with its capitals' top at UI (x, y). '\n' starts a new line 12
// units down, matching M_WriteText.
void DoomPerf_MenuDrawText(int x, int y, int style, int tone, const char* s)
{
    char line[128];
    int n, baseline;

    if (!dp_mf_built)
	DP_MF_Build();
    if (tone < 0 || tone >= DP_MF_TONES)
	tone = 0;
    while (*s)
    {
	for (n = 0; s[n] && s[n] != '\n' && n < (int)sizeof(line) - 1; n++)
	    line[n] = s[n];
	line[n] = 0;
	baseline = y * DP_MF_SCALE + DP_MF_Cap(style) * DP_MF_Pix(style);
	DP_MF_Pass(x * DP_MF_SCALE, baseline, style, tone, line, 1);
	DP_MF_Pass(x * DP_MF_SCALE, baseline, style, tone, line, 0);
	s += n;
	if (*s == '\n')
	    s++;
	y += 12;
    }
    V_MarkRect(0, 0, SCREENWIDTH, SCREENHEIGHT);
}

#else

int DoomPerf_MenuFontAvailable(void)
{
    return 0;
}

int DoomPerf_MenuTextWidth(int style, const char* s)
{
    (void)style; (void)s;
    return 0;
}

void DoomPerf_MenuDrawText(int x, int y, int style, int tone, const char* s)
{
    (void)x; (void)y; (void)style; (void)tone; (void)s;
}

#endif
