// GENERATED by scripts/build-doomperf-map.mjs — do not edit by hand.
// Map interaction geometry shared with the browser UI (src/index.ts).
export const mapManifest = {
  "useRange": 64,
  "doorOpenThreshold": 16,
  "terminals": [
    {
      "sign": "cores",
      "segments": [
        {
          "ax": -128,
          "ay": 1624,
          "bx": 128,
          "by": 1624
        }
      ]
    },
    {
      "sign": "runqueue",
      "segments": [
        {
          "ax": -640,
          "ay": 1312,
          "bx": -384,
          "by": 1312
        }
      ]
    },
    {
      "sign": "load",
      "segments": [
        {
          "ax": 506,
          "ay": 1676,
          "bx": 762,
          "by": 1676
        }
      ]
    },
    {
      "sign": "memory",
      "segments": [
        {
          "ax": 1520,
          "ay": 128,
          "bx": 1520,
          "by": -128
        }
      ]
    },
    {
      "sign": "memory-rss",
      "segments": [
        {
          "ax": 1088,
          "ay": 768,
          "bx": 1216,
          "by": 768
        }
      ]
    },
    {
      "sign": "memory-pressure",
      "segments": [
        {
          "ax": 1408,
          "ay": 448,
          "bx": 1408,
          "by": 256
        }
      ]
    },
    {
      "sign": "memory-swap",
      "segments": [
        {
          "ax": 1408,
          "ay": -256,
          "bx": 1408,
          "by": -448
        }
      ]
    },
    {
      "sign": "memory-oom",
      "segments": [
        {
          "ax": 1152,
          "ay": -672,
          "bx": 1248,
          "by": -672
        }
      ]
    },
    {
      "sign": "storage",
      "segments": [
        {
          "ax": 128,
          "ay": -1776,
          "bx": -128,
          "by": -1776
        }
      ]
    },
    {
      "sign": "network",
      "segments": [
        {
          "ax": -1760,
          "ay": -128,
          "bx": -1760,
          "by": 128
        }
      ]
    }
  ],
  "easterEggs": [
    {
      "id": "disk-server-rack",
      "segments": [
        {
          "ax": 288,
          "ay": -1424,
          "bx": 288,
          "by": -1520
        },
        {
          "ax": 384,
          "ay": -1520,
          "bx": 288,
          "by": -1520
        }
      ]
    }
  ],
  "doors": [
    {
      "segments": [
        {
          "ax": -96,
          "ay": 384,
          "bx": 96,
          "by": 384
        },
        {
          "ax": -96,
          "ay": 448,
          "bx": 96,
          "by": 448
        }
      ],
      "probeX": 0,
      "probeY": 416
    },
    {
      "segments": [
        {
          "ax": 384,
          "ay": -96,
          "bx": 384,
          "by": 96
        },
        {
          "ax": 448,
          "ay": -96,
          "bx": 448,
          "by": 96
        }
      ],
      "probeX": 416,
      "probeY": 0
    },
    {
      "segments": [
        {
          "ax": -96,
          "ay": -384,
          "bx": 96,
          "by": -384
        },
        {
          "ax": -96,
          "ay": -448,
          "bx": 96,
          "by": -448
        }
      ],
      "probeX": 0,
      "probeY": -416
    },
    {
      "segments": [
        {
          "ax": -384,
          "ay": -96,
          "bx": -384,
          "by": 96
        },
        {
          "ax": -448,
          "ay": -96,
          "bx": -448,
          "by": 96
        }
      ],
      "probeX": -416,
      "probeY": 0
    }
  ]
} as const;
