// GENERATED by scripts/build-doomperf-map.mjs — do not edit by hand.
// Map interaction geometry shared with the browser UI (src/index.ts).
export const mapManifest = {
  "useRange": 64,
  "doorOpenThreshold": 16,
  "terminals": [
    {
      "sign": "cores",
      "segments": [
        {
          "ax": -128,
          "ay": 1624,
          "bx": 128,
          "by": 1624
        }
      ]
    },
    {
      "sign": "runqueue",
      "segments": [
        {
          "ax": -704,
          "ay": 1496,
          "bx": -448,
          "by": 1496
        }
      ]
    },
    {
      "sign": "load",
      "segments": [
        {
          "ax": 448,
          "ay": 1496,
          "bx": 704,
          "by": 1496
        }
      ]
    }
  ],
  "doors": [
    {
      "segments": [
        {
          "ax": -96,
          "ay": 384,
          "bx": 96,
          "by": 384
        },
        {
          "ax": -96,
          "ay": 448,
          "bx": 96,
          "by": 448
        }
      ],
      "probeX": 0,
      "probeY": 416
    },
    {
      "segments": [
        {
          "ax": 384,
          "ay": -96,
          "bx": 384,
          "by": 96
        },
        {
          "ax": 448,
          "ay": -96,
          "bx": 448,
          "by": 96
        }
      ],
      "probeX": 416,
      "probeY": 0
    },
    {
      "segments": [
        {
          "ax": -96,
          "ay": -384,
          "bx": 96,
          "by": -384
        },
        {
          "ax": -96,
          "ay": -448,
          "bx": 96,
          "by": -448
        }
      ],
      "probeX": 0,
      "probeY": -416
    },
    {
      "segments": [
        {
          "ax": -384,
          "ay": -96,
          "bx": -384,
          "by": 96
        },
        {
          "ax": -448,
          "ay": -96,
          "bx": -448,
          "by": 96
        }
      ],
      "probeX": -416,
      "probeY": 0
    }
  ]
} as const;
