// GENERATED by scripts/build-doomperf-map.mjs — do not edit by hand.
// Map interaction geometry shared with the browser UI (src/index.ts).
export const mapManifest = {
  "useRange": 64,
  "doorOpenThreshold": 16,
  "terminals": [
    {
      "sign": "cores",
      "segments": [
        {
          "ax": -128,
          "ay": 1624,
          "bx": 128,
          "by": 1624
        }
      ]
    },
    {
      "sign": "runqueue",
      "segments": [
        {
          "ax": -896,
          "ay": 1312,
          "bx": -640,
          "by": 1312
        }
      ]
    },
    {
      "sign": "load",
      "segments": [
        {
          "ax": 762,
          "ay": 1456,
          "bx": 1018,
          "by": 1456
        }
      ]
    },
    {
      "sign": "memory",
      "segments": [
        {
          "ax": 768,
          "ay": 272,
          "bx": 1024,
          "by": 272
        }
      ]
    },
    {
      "sign": "memory-rss",
      "segments": [
        {
          "ax": 2149,
          "ay": 304,
          "bx": 2405,
          "by": 304
        }
      ]
    },
    {
      "sign": "memory-oom",
      "segments": [
        {
          "ax": 2149,
          "ay": -304,
          "bx": 2405,
          "by": -304
        }
      ]
    },
    {
      "sign": "memory-reclaim",
      "segments": [
        {
          "ax": 1472,
          "ay": 1109,
          "bx": 1728,
          "by": 1109
        }
      ]
    },
    {
      "sign": "memory-faults",
      "segments": [
        {
          "ax": 1928,
          "ay": -517,
          "bx": 1928,
          "by": -773
        }
      ]
    },
    {
      "sign": "storage-usage",
      "segments": [
        {
          "ax": -600,
          "ay": -1177,
          "bx": -856,
          "by": -1177
        }
      ]
    },
    {
      "sign": "storage-iops",
      "segments": [
        {
          "ax": 846,
          "ay": -1481,
          "bx": 590,
          "by": -1481
        }
      ]
    },
    {
      "sign": "storage-queue",
      "segments": [
        {
          "ax": 782,
          "ay": -917,
          "bx": 782,
          "by": -1173
        }
      ]
    },
    {
      "sign": "network",
      "segments": [
        {
          "ax": -1760,
          "ay": -128,
          "bx": -1760,
          "by": 128
        }
      ]
    },
    {
      "sign": "network-queues",
      "segments": [
        {
          "ax": -1232,
          "ay": -456,
          "bx": -1360,
          "by": -456
        }
      ]
    },
    {
      "sign": "network-sockets",
      "segments": [
        {
          "ax": -1184,
          "ay": 456,
          "bx": -1312,
          "by": 456
        }
      ]
    }
  ],
  "easterEggs": [
    {
      "id": "disk-server-rack",
      "segments": [
        {
          "ax": -160,
          "ay": -1882,
          "bx": -160,
          "by": -1946
        }
      ]
    }
  ],
  "doors": [
    {
      "segments": [
        {
          "ax": -96,
          "ay": 384,
          "bx": 96,
          "by": 384
        },
        {
          "ax": -96,
          "ay": 448,
          "bx": 96,
          "by": 448
        }
      ],
      "probeX": 0,
      "probeY": 416
    },
    {
      "segments": [
        {
          "ax": 384,
          "ay": -96,
          "bx": 384,
          "by": 96
        },
        {
          "ax": 448,
          "ay": -96,
          "bx": 448,
          "by": 96
        }
      ],
      "probeX": 416,
      "probeY": 0
    },
    {
      "segments": [
        {
          "ax": -96,
          "ay": -384,
          "bx": 96,
          "by": -384
        },
        {
          "ax": -96,
          "ay": -448,
          "bx": 96,
          "by": -448
        }
      ],
      "probeX": 0,
      "probeY": -416
    },
    {
      "segments": [
        {
          "ax": -384,
          "ay": -96,
          "bx": -384,
          "by": 96
        },
        {
          "ax": -448,
          "ay": -96,
          "bx": -448,
          "by": 96
        }
      ],
      "probeX": -416,
      "probeY": 0
    }
  ]
} as const;
